name: Lint

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run black, flake8, isort
        uses: nens/pre-commit-action@main
